add files to teach poses in grasplan with gazebo
DFKI-NI/mobipick pull request #13
Opened 2023-11-27 17:15 UTC by oscar-lima

Files required by Grasplan to record grasps using Gazebo simulation. The idea is to spawn only the Mobipick gripper in simulation and control it via velocity commands in a free-floating world with no gravity,

see https://youtu.be/osATE2MKjYU?si=Z3yQiFkM0wS_GKPl

2023-11-28 15:17 UTC, mintar requested changes
* [x] There *was* an error about the missing gazebo_ros_vel package, but I've already fixed it:

  ```
  [Err] [Plugin.hh:212] Failed to load plugin libgazebo_ros_vel.so: libgazebo_ros_vel.so: cannot open shared object file: No such file or directory
  ```

  I've added a commit that clones https://github.com/aprilprojecteu/april_gazebo_plugins

* [x] The file `worlds/zero_gravity_empty_world.sdf` is missing (although Gazebo doesn't print an error unfortunately). Did you forget to commit it?

* [ ] There are some errors printed regarding the `gazebo_grasp_plugin`:

  ```
  [Err] [GazeboGraspGripper.cpp:64] GazeboGraspGripper: Palm link robotiq_arg2f/ur5_wrist_3_link not found. The gazebo grasp plugin will not work.
  [Err] [GazeboGraspFix.cpp:231] GazeboGraspFix: Could not initialize arm arm. Skipping.
  [Err] [GazeboGraspFix.cpp:261] ERROR: GazeboGraspFix: Cannot use a GazeboGraspFix because no arms were configured successfully. Plugin will not work.
  ```

  There's a line `<xacro:property name="grasp_fix_required" value="false" />`, but I don't think it does anything.

2023-11-29 13:35 UTC, oscar-lima commented
Hi Martin, thanks for the feedback!

The documentation about how to launch it can be found [here](https://grasplan-documentation.readthedocs.io/en/latest/grasp-planners/handcoded-grasp-planner/recording-grasps.html) which is basically:

```roslaunch grasplan teach_grasp_poses_gazebo.launch```

Missing zero_gravity_empty_world.sdf pushed via: https://github.com/DFKI-NI/mobipick/commit/87b6f2727888a1853b4ebc64ac8f1fd8e7283e98

GazeboGraspFix related errors, fixed via : https://github.com/DFKI-NI/mobipick/commit/c5d0771a5dabd4816a77370f4e2963bb7f4a9f74

2023-11-30 11:20 UTC, mintar approved these changes

2023-11-30 11:20 UTC, merged

2023-11-30 11:21 UTC, mintar commented
Great, tested and working!